Dynamic php version grabbing

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -100,6 +100,26 @@ fi
 engine="php"
 engine_r="php -r"
 
+# ECHO PHP VERSION
+if [[ -f "composer.json" ]]; then
+    if [[ ! -f "composer.lock" ]]; then
+        cat composer.json | python -c 'import sys, json; print sys.exit(any(key.count("/") for key in json.load(sys.stdin).get("require", {})))' 2> /dev/null || error "Your composer.json has dependencies, but no composer.lock
+was found, check it into your repository alongside composer.json!"
+    fi
+    
+    solver_payload=$(echo -n "$runtimes" | python -c '
+import sys, json
+ret = {}
+c_json = dict(json.load(open("composer.json"))) # wrap in dict() to prevent simple errors with {} vs []
+ret["platform"] = {k: dict(c_json.get("require", {})).get(k, None) for k in ["php"]} # wrap in dict() to prevent simple errors with {} vs []
+print json.dumps(ret["platform"]["php"]).replace("\"", "")
+' 2> /dev/null) || error "Couldn't parse composer.lock; it must be valid JSON.
+Run 'composer update' to have it re-generated by Composer."
+    echo -n "Using PHP version: $solver_payload - This should be a specific, exact version and NOT >x.x.x or ~x.x.x"
+    echo -n ' '
+    PHP_VERSION="$solver_payload"
+fi
+
 
 status "Installing system packages..."
 
